### ISSUE TITLE
Problem with this Library

### ISSUE THREAD

**Issue by ChrisWesterfield** [darookee/u2f-two-factor-bundle#1]
Hi,
I included  your bundle within my project.
But it will not work.
Everytime I try to validate my Yubikey Neo 4 device I get the following message:

Error in U2F.php line 266:
No matching request found

This is the Part where it seems to break (within the U2F Library)

    foreach ($requests as $req) {
          if( !is_object( $req ) ) {
          	throw new \InvalidArgumentException('$requests of doAuthenticate() method only accepts array of object.');
      }
      if($req->keyHandle === $response->keyHandle && $req->challenge === $decodedClient->challenge) {
            break;
      }
      $req = null;
    }
    if($req === null) {
      throw new Error('No matching request found', ERR_NO_MATCHING_REQUEST );
    }

The keyHandle is matching, but the challenge is not matching.
What am I doing wrong?
I really would like to include this using your bundle.
But I don't really know where the problem is.
When the request is sent, the challange is sent to symfony.
But the U2F returns a different Challenge.
I don't really know why.

**Comment by darookee** [comment]
I had a similar error while developing this and now I finaly remembered what the problem was. Are you accessing your project running with `bin/console server:run`? U2F seems to require a https connection and I remember getting a different 'host' in the JavaScript, before the request is sent to the server than [here](https://github.com/darookee/u2f-two-factor-bundle/blob/master/Security/TwoFactor/Prodiver/U2F/U2FAuthenticator.php#L29).
Could you please confirm that you are accessing your project via https and a valid hostname? I think `localhost` should also work...

**Comment by darookee** [comment]
Do you still experience this problem or could you solve it?

**Comment by ChrisWesterfield** [comment]
I tried it again and still experience the same issue.
I double checked that I am using https and the correct host.
If I check the Response and the original request they are different from each other.

On Line 276 from the U2F.php Library

$req->keyHandle === $response->keyHandle

are equal

but

$req->challenge === $decodedClient->challenge

are not.
This is the reason why I get an no matching request found.

**Comment by darookee** [comment]
Can you check if your `U2F->$appId` matches your browser URL. The `$appId` is generated [here](https://github.com/darookee/u2f-two-factor-bundle/blob/master/Security/TwoFactor/Prodiver/U2F/U2FAuthenticator.php#L29), basically the URL of your project.

**Comment by ChrisWesterfield** [comment]
Ok,
I checked it.
Here is the Output:

object(u2flib_server\U2F)#614 (3) {
  ["appId":"u2flib_server\U2F":private]=>
  string(18) "https://subdomain.domain.tld"

It matches the URL of the vhost and the URL I access it.
The Only difference is, that I add a app_dev.php/ after the domain stuff.


I also checked the keyvalue and challange.
Keyvalues match, but challenge does not.
It's the only thing that differs.
But I don't understand why.

**Comment by ChrisWesterfield** [comment]
Ok,
first thing that I found out, was that the certificat column stored only 255 Characters in the entity.
After expanding it to text the certificate is stored completly.
But still the challenge are different.

**Comment by ChrisWesterfield** [comment]
Hi,
currently trying to resolve this and find an solution.

Here is a dump of the decodedClient and request from Inside of the doAuthenticate Method of the U2F Library:

$decodedClient
object(stdClass)#117 (4) {
  ["typ"]=>
  string(25) "navigator.id.getAssertion"
  ["challenge"]=>
  string(43) "cGnTZWrj0h2y9HMma4144a0md-3VB7ifq3eLMSBnKHw"
  ["origin"]=>
  string(28) "xxxxxx"
  ["cid_pubkey"]=>
  string(6) "unused"
}
$request
array(1) {
  [0]=>
  object(stdClass)#154 (4) {
    ["version"]=>
    string(6) "U2F_V2"
    ["challenge"]=>
    string(43) "Khq5TV95LSpkGjT7h4wFCjxRtrVd8YrIl-zJTymzthU"
    ["keyHandle"]=>
    string(86) "XYTXYTRXYTTXYT"
    ["appId"]=>
    string(28) "xxxxxx"
  }
}
$response
object(stdClass)#86 (3) {
  ["keyHandle"]=>
  string(86) "XYTXYTRXYTTXYT"
  ["clientData"]=>
  string(207) "xxxxxxxxxxxxxxxx(Equals the $decodedClient Data)"
  ["signatureData"]=>
  string(100) "SIGNATURE"
}

I only masked the Yubikey Specific fields to protect my keys.
Where is the Problem.
I can't really see it.
Is it an Bug in the U2F Library?

**Comment by ChrisWesterfield** [comment]
I believe I found the reason why it is behaving strange on my system.

I compared and debuged for quite a while and found the issue.

I am using redis as a session storage.
If I store the u2f_authentication in the session and use it to retrieve the data from the session during the requestAuthenticationCode method I get different data then in the request is sent.
So both challanges differ from each other.
I am using Symfony 3 Framework with the snc redis cache.

I dug into it even deeper.
It seems that the Developer Toolbar or any other component sets a second response to the system and overwrites the session data which is kept for counter challenge.

I buy passed this currently with the following implementation:

`    public function requestAuthenticationCode(AuthenticationContext $context)
    {
        $user = $context->getUser();
        $request = $context->getRequest();
        $session = $context->getSession();
        $authData = $request->get($this->authCodeParameter);
        if (null !== $authData) {
            if ($this->authenticator->checkRequest(
                $user,
                json_decode($session->get('u2f_authentication')),
                json_decode($authData)
            )) {
                $context->setAuthenticated(true);
                $session->remove('u2f_authentication');
                return new RedirectResponse($request->getUri());
            } else {
                $session->getFlashBag()->set('two_factor', 'r_u2f_two_factor.code_invalid');
            }
        }
        if(!$session->has('u2f_authentication')) {
            $authenticationData = json_encode($this->authenticator->generateRequest($user), JSON_UNESCAPED_SLASHES);
            $session->set('u2f_authentication', $authenticationData);
        }
        else
        {
            $authenticationData = $session->get('u2f_authentication');
        }
        return $this->templating->renderResponse($this->formTemplate, array(
            'authenticationData' => $authenticationData,
            'useTrustedOption' => $context->useTrustedOption(),
        ));
    }`

But I'm not shure how secured it is, so please let me know what you think of this solution.

**Comment by darookee** [comment]
Sorry it took so long for me to answer.

It's been a while since I last tested this, but I think I also had problems with the debug toolbar, even without redis, when using this so I didn't use the toolbar. I fear that there is nothing I can do to fix this, because this would probably be part of the security measures that are taken to prevent false requests.

I'd suggest not to use the workaround in production.
