### ISSUE TITLE
Does not work for non root domain name

### ISSUE THREAD

**Issue by tarioch** [darookee/u2f-two-factor-bundle#12]
As far as I'm able to tell, this only works if the app is deployed on a root domain. e.g. https://mydomain.tld

It does not work if it's deployed in a path such as https://mydomain.tld/myapp/

**Comment by darookee** [comment]
I'll look into it...

**Comment by darookee** [comment]
It's been a few days... But I just took a quick look and believe that it's probably because the scripts are not beeing loaded, as they point to `/bundles`. Could you confirm that, if you still have somewhere to test this?

**Comment by tarioch** [comment]
I actually deployed it as root in the meantime. So I can't test it.
