### ISSUE TITLE
Not able to register token

### ISSUE THREAD

**Issue by tarioch** [darookee/u2f-two-factor-bundle#13]
If I go to /u2f_register I see the text field for "Name your FIDO-Device" and after this just the number "2". I'm using the latest chrome and my fido device works fine on other sites.

**Comment by tarioch** [comment]
I'm getting it running with latest u2f-api.js and some changes, will send a pull request later.

**Comment by darookee** [comment]
Thanks! I'll merge it as soon as I can...

**Comment by tarioch** [comment]
Created, see #14 

I'll probably do some more improvements, like splitting the name of the token from the site, as this currently prevents registration from android (the auth app opens directly when going to the page and therefore it's not possible to enter a name for the token).

Also I think it would be useful to have a text on the site when you need to press the button on the token.

**Comment by darookee** [comment]
This is fixed in #14
