### ISSUE TITLE
How to use it with other two-factor tokens?

### ISSUE THREAD

**Issue by stephanvierkant** [darookee/u2f-two-factor-bundle#18]
If I've enabled the Google Authenticator, `RU2FTwoFactorBundle:Authentication/form.html.twig` won't be showed.

How to get a form that gives the user the option to enter the 6 digit code ór push the U2F button?

See https://github.com/scheb/two-factor-bundle/issues/112.

**Comment by darookee** [comment]
That behavior is not implemented.

See https://github.com/scheb/two-factor-bundle/issues/112#issuecomment-369230841

**Comment by stephanvierkant** [comment]
Well, not yet. v3.0.0-beta1 has just been released and support this behavior.
