### ISSUE TITLE
Typo in namespace: Prodiver instead of Provider

### ISSUE THREAD

**Issue by stephanvierkant** [darookee/u2f-two-factor-bundle#19]
Fixing this would be a BC problem. What are your thoughts?

**Comment by darookee** [comment]
First of all: damn...
Than, thanks for reporting this.
And finally I'd say I add the classes under the correct namespace, keeping the incorrect ones. All future changes will be in the classes in the correct namespace. That way old projects still can use it. I also will trigger a E_USER_DEPRECATED in the constructor of the 'old' classes.
