### ISSUE TITLE
Scheb 3.2 compatibility

### ISSUE THREAD

**Issue by stephanvierkant** [darookee/u2f-two-factor-bundle#21]
FYI: I'm working on making this bundle compatible with the new 3.2 release: https://github.com/scheb/two-factor-bundle/releases/tag/v3.2.0

This new version makes it possible to use multiple multi-factor authentication methods, so a user can choose between U2F or TOTP.

**Comment by darookee** [comment]
Thank you!
So #20 is just the first PR? Then I'd wait until you're done and merge everything in one go...
