### ISSUE TITLE
r_u2f_two_factor !== ru2_f_two_factor

### ISSUE THREAD

**Issue by PhilETaylor** [darookee/u2f-two-factor-bundle#38]
Still doesnt work 

#4 was reported in 2016.... 

Symfony 4.3 (and before) the yaml for configuration uses a root of `ru2_f_two_factor` whereas Dependency Injection uses `r_u2f_two_factor`

**Choose one, and stick with it for documentation, and dependency injection.** 

see: https://github.com/darookee/u2f-two-factor-bundle/blob/c1b5319fd644425455bc0e9968b6144ca53ae602/DependencyInjection/Configuration.php#L20

```
ru2_f_two_factor:
  formTemplate: bundles/RU2FTwoFactorBundle/Authentication/form.html.twig
  registerTemplate: bundles/RU2FTwoFactorBundle/Registration/register.html.twig
```

![Screenshot 2019-05-30 at 18 21 45](https://user-images.githubusercontent.com/400092/58650959-f4685a00-8307-11e9-9522-4362cfa93bbc.png)

For now Ive reverted back to my old old fork of this repo :(

**Comment by stephanvierkant** [comment]
I agree, having two strings is very confusing. I created a Pull Request (something you could have done as well ;)).

#4 was fixed BTW, maybe this is a regression?

**Comment by PhilETaylor** [comment]
> I created a Pull Request (something you could have done as well ;)).

I was too busy trying to fight the fire that caused my production app used by 1000s from being down after composer upgraded this :) 

it was on my list to cycle back to once things calmed down :)

**Comment by darookee** [comment]
Thanks for the PR @stephanvierkant. @PhilETaylor I hope this fixes your problem, sorry it took that long. I hope to have more time to maintain this next month... :-|

**Comment by PhilETaylor** [comment]
fixes one problem but then there are others. This is not yet ready for Symfony 4.2/4.3 :(
