### ISSUE TITLE
Symfony 4 compat

### ISSUE THREAD

**Issue by PhilETaylor** [darookee/u2f-two-factor-bundle#40]
Running d9c5ad3430dc7df97e852890653982737ef31ec3

Browsing to:
/u2f_register

I get:

<img width="1094" alt="Screenshot 2019-06-05 at 13 04 32" src="https://user-images.githubusercontent.com/400092/58954996-a2ee1e00-8792-11e9-909c-0eb390a6563f.png">

If I then attempt to force this controller as public in services, then it complains that one of the construct params is a string.

**Comment by darookee** [comment]
Thanks @stephanvierkant
