### ISSUE TITLE
v0.7.0 not available in composer

### ISSUE THREAD

**Issue by PhilETaylor** [darookee/u2f-two-factor-bundle#42]
Looks like you have not synced your packagist.org account with the repo as v0.7.0 is not available

https://packagist.org/packages/r/u2f-two-factor-bundle

This leads to a composer install error:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package r/u2f-two-factor-bundle 0.7.0 exists as r/u2f-two-factor-bundle[0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6, 0.6.1, 0.6.2, dev-master] but these are rejected by your constraint.
```

v0.7.0 does seem to have full Symfony 4.3.1 compatibility and works well - thanks for that.

**Comment by darookee** [comment]
It shows 0.7.0 now. Maybe logging in to packagist was all that was needed to make it sync again... :-/

**Comment by PhilETaylor** [comment]
:-) cool I'll pull now and run my final tests before deploying to production - thanks.
