### ISSUE TITLE
[Docs] Doctrine Type of certificate can't be string

### ISSUE THREAD

**Issue by binarious** [darookee/u2f-two-factor-bundle#5]
`certificate` is of type `string` in the docs, but this would result in the following error:
```
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'certificate' at row 1
```

**Comment by darookee** [comment]
Hi!
Thanks for the PRs. I either did not get notified or just overlooked them, sorry for that.
This Bundle is not 'dead', but I didn't have much time lately to update it for the new version of the TwoFactorBundle. If you are interested I could give you push permissions.

**Comment by binarious** [comment]
No problem. Great to know that this Bundle is still 'alive'. PRs work fine for me when they receive attention in some days, but if you don't have enough time, feel free to give me the permissions. I'm happy to help.
